### ISSUE TITLE
svg图标用样式color属性修改不了颜色

### ISSUE THREAD

**Issue by ok111net** [ant-design/antd-mobile-icons-v2#4]
svg图标用样式color属性修改不了颜色，原因已找到，是因为svg里写死了颜色：
<circle fill="#4A4A4A" cx="29.767" cy="19.63"　....../>
<path fill="#4A4A4A" d="M22.102,4.　....../>

这里的fill属性要去掉，然后让用户自己用color样式去重写自己的颜色

**Comment by paranoidjk** [comment]
```css
.am-icon {
  fill: red;
}
```
